/****************************************************************************************************
 *                                                                                                  *
 *                                           HTML Colors                                            *
 *                                                                                                  *
 * Copyright © 2016 Abyss Morgan. All rights reserved.                                              *
 *                                                                                                  *
 * Download: https://github.com/AbyssMorgan/SA-MP/tree/master/include/SAM                           *
 *                                                                                                  *
 * Plugins: None                                                                                    *
 * Modules: None                                                                                    *
 *                                                                                                  *
 * File Version: 1.0.1                                                                              *
 * SA:MP Version: 0.3.7                                                                             *
 *                                                                                                  *
 ****************************************************************************************************/

#if defined _HTML_Color
	#endinput
#endif
#define _HTML_Color

//		name					0xRGBA
#define white					0xFFFFFFFF
#define gray					0x808080FF
#define silver					0xC0C0C0FF
#define black					0x000000FF
#define maroon					0x800000FF
#define red						0xFF0000FF
#define purple					0x800080FF
#define fuchsia					0xFF00FFFF
#define green					0x008000FF
#define lime					0x00FF00FF
#define olive					0x808000FF
#define yellow					0xFFFF00FF
#define navy					0x000080FF
#define blue					0x0000FFFF
#define teal					0x008080FF
#define aqua					0x00FFFFFF
#define orange					0xFFA500FF
#define indianred				0xCD5C5CFF
#define lightcoral				0xF08080FF
#define salmon					0xFA8072FF
#define darksalmon				0xE9967AFF
#define lightsalmon				0xFFA07AFF
#define crimson					0xDC143CFF
#define red						0xFF0000FF
#define firebrick				0xB22222FF
#define darkred					0x8B0000FF
#define pink					0xFFC0CBFF
#define lightpink				0xFFB6C1FF
#define hotpink					0xFF69B4FF
#define deeppink				0xFF1493FF
#define mediumvioletred			0xC71585FF
#define palevioletred			0xDB7093FF
#define lightsalmon				0xFFA07AFF
#define coral					0xFF7F50FF
#define tomato					0xFF6347FF
#define orangered				0xFF4500FF
#define darkorange				0xFF8C00FF
#define orange					0xFFA500FF
#define gold					0xFFD700FF
#define yellow					0xFFFF00FF
#define lightyellow				0xFFFFE0FF
#define lemonchiffon			0xFFFACDFF
#define lightgoldenrodyellow	0xFAFAD2FF
#define papayawhip				0xFFEFD5FF
#define moccasin				0xFFE4B5FF
#define peachpuff				0xFFDAB9FF
#define palegoldenrod			0xEEE8AAFF
#define khaki					0xF0E68CFF
#define darkkhaki				0xBDB76BFF
#define lavender				0xE6E6FAFF
#define thistle					0xD8BFD8FF
#define plum					0xDDA0DDFF
#define violet					0xEE82EEFF
#define orchid					0xDA70D6FF
#define fuchsia					0xFF00FFFF
#define magenta					0xFF00FFFF
#define mediumorchid			0xBA55D3FF
#define mediumpurple			0x9370DBFF
#define blueviolet				0x8A2BE2FF
#define darkviolet				0x9400D3FF
#define darkorchid				0x9932CCFF
#define darkmagenta				0x8B008BFF
#define purple					0x800080FF
#define indigo					0x4B0082FF
#define slateblue				0x6A5ACDFF
#define darkslateblue			0x483D8BFF
#define mediumslateblue			0x7B68EEFF
#define greenyellow				0xADFF2FFF
#define chartreuse				0x7FFF00FF
#define lawngreen				0x7CFC00FF
#define lime					0x00FF00FF
#define limegreen				0x32CD32FF
#define palegreen				0x98FB98FF
#define lightgreen				0x90EE90FF
#define mediumspringgreen		0x00FA9AFF
#define springgreen				0x00FF7FFF
#define mediumseagreen			0x3CB371FF
#define seagreen				0x2E8B57FF
#define forestgreen				0x228B22FF
#define green					0x008000FF
#define darkgreen				0x006400FF
#define yellowgreen				0x9ACD32FF
#define olivedrab				0x6B8E23FF
#define olive					0x808000FF
#define darkolivegreen			0x556B2FFF
#define mediumaquamarine		0x66CDAAFF
#define darkseagreen			0x8FBC8FFF
#define lightseagreen			0x20B2AAFF
#define darkcyan				0x008B8BFF
#define teal					0x008080FF
#define aqua					0x00FFFFFF
#define cyan					0x00FFFFFF
#define lightcyan				0xE0FFFFFF
#define paleturquoise			0xAFEEEEFF
#define aquamarine				0x7FFFD4FF
#define turquoise				0x40E0D0FF
#define mediumturquoise			0x48D1CCFF
#define darkturquoise			0x00CED1FF
#define cadetblue				0x5F9EA0FF
#define steelblue				0x4682B4FF
#define lightsteelblue			0xB0C4DEFF
#define powderblue				0xB0E0E6FF
#define lightblue				0xADD8E6FF
#define skyblue					0x87CEEBFF
#define lightskyblue			0x87CEFAFF
#define deepskyblue				0x00BFFFFF
#define dodgerblue				0x1E90FFFF
#define cornflowerblue			0x6495EDFF
#define mediumslateblue			0x7B68EEFF
#define royalblue				0x4169E1FF
#define blue					0x0000FFFF
#define mediumblue				0x0000CDFF
#define darkblue				0x00008BFF
#define navy					0x000080FF
#define midnightblue			0x191970FF
#define cornsilk				0xFFF8DCFF
#define blanchedalmond			0xFFEBCDFF
#define bisque					0xFFE4C4FF
#define navajowhite				0xFFDEADFF
#define wheat					0xF5DEB3FF
#define burlywood				0xDEB887FF
#define tan						0xD2B48CFF
#define rosybrown				0xBC8F8FFF
#define sandybrown				0xF4A460FF
#define goldenrod				0xDAA520FF
#define darkgoldenrod			0xB8860BFF
#define peru					0xCD853FFF
#define chocolate				0xD2691EFF
#define saddlebrown				0x8B4513FF
#define sienna					0xA0522DFF
#define brown					0xA52A2AFF
#define maroon					0x800000FF
#define white					0xFFFFFFFF
#define snow					0xFFFAFAFF
#define honeydew				0xF0FFF0FF
#define mintcream				0xF5FFFAFF
#define azure					0xF0FFFFFF
#define aliceblue				0xF0F8FFFF
#define ghostwhite				0xF8F8FFFF
#define whitesmoke				0xF5F5F5FF
#define seashell				0xFFF5EEFF
#define beige					0xF5F5DCFF
#define oldlace					0xFDF5E6FF
#define floralwhite				0xFFFAF0FF
#define ivory					0xFFFFF0FF
#define antiquewhite			0xFAEBD7FF
#define linen					0xFAF0E6FF
#define lavenderblush			0xFFF0F5FF
#define mistyrose				0xFFE4E1FF
#define gainsboro				0xDCDCDCFF
#define lightgrey				0xD3D3D3FF
#define silver					0xC0C0C0FF
#define darkgray				0xA9A9A9FF
#define gray					0x808080FF
#define dimgray					0x696969FF
#define lightslategray			0x778899FF
#define slategray				0x708090FF
#define darkslategray			0x2F4F4FFF
#define black					0x000000FF

//EOF