/****************************************************************************************************
 *                                                                                                  *
 *                                           HTML Colors                                            *
 *                                                                                                  *
 * Copyright © 2016 Abyss Morgan. All rights reserved.                                              *
 *                                                                                                  *
 * Download: https://github.com/AbyssMorgan/SA-MP/tree/master/include/SAM                           *
 *                                                                                                  *
 * Plugins: None                                                                                    *
 * Modules: None                                                                                    *
 *                                                                                                  *
 * File Version: 1.0.1                                                                              *
 * SA:MP Version: 0.3.7                                                                             *
 *                                                                                                  *
 ****************************************************************************************************/

#if defined _HTML_Color
	#endinput
#endif
#define _HTML_Color

//		name						0xRGBA
#define Color_white					0xFFFFFFFF
#define Color_gray					0x808080FF
#define Color_silver				0xC0C0C0FF
#define Color_black					0x000000FF
#define Color_maroon				0x800000FF
#define Color_red					0xFF0000FF
#define Color_purple				0x800080FF
#define Color_fuchsia				0xFF00FFFF
#define Color_green					0x008000FF
#define Color_lime					0x00FF00FF
#define Color_olive					0x808000FF
#define Color_yellow				0xFFFF00FF
#define Color_navy					0x000080FF
#define Color_blue					0x0000FFFF
#define Color_teal					0x008080FF
#define Color_aqua					0x00FFFFFF
#define Color_orange				0xFFA500FF
#define Color_indianred				0xCD5C5CFF
#define Color_lightcoral			0xF08080FF
#define Color_salmon				0xFA8072FF
#define Color_darksalmon			0xE9967AFF
#define Color_lightsalmon			0xFFA07AFF
#define Color_crimson				0xDC143CFF
#define Color_red					0xFF0000FF
#define Color_firebrick				0xB22222FF
#define Color_darkred				0x8B0000FF
#define Color_pink					0xFFC0CBFF
#define Color_lightpink				0xFFB6C1FF
#define Color_hotpink				0xFF69B4FF
#define Color_deeppink				0xFF1493FF
#define Color_mediumvioletred		0xC71585FF
#define Color_palevioletred			0xDB7093FF
#define Color_lightsalmon			0xFFA07AFF
#define Color_coral					0xFF7F50FF
#define Color_tomato				0xFF6347FF
#define Color_orangered				0xFF4500FF
#define Color_darkorange			0xFF8C00FF
#define Color_orange				0xFFA500FF
#define Color_gold					0xFFD700FF
#define Color_yellow				0xFFFF00FF
#define Color_lightyellow			0xFFFFE0FF
#define Color_lemonchiffon			0xFFFACDFF
#define Color_lightgoldenrodyellow	0xFAFAD2FF
#define Color_papayawhip			0xFFEFD5FF
#define Color_moccasin				0xFFE4B5FF
#define Color_peachpuff				0xFFDAB9FF
#define Color_palegoldenrod			0xEEE8AAFF
#define Color_khaki					0xF0E68CFF
#define Color_darkkhaki				0xBDB76BFF
#define Color_lavender				0xE6E6FAFF
#define Color_thistle				0xD8BFD8FF
#define Color_plum					0xDDA0DDFF
#define Color_violet				0xEE82EEFF
#define Color_orchid				0xDA70D6FF
#define Color_fuchsia				0xFF00FFFF
#define Color_magenta				0xFF00FFFF
#define Color_mediumorchid			0xBA55D3FF
#define Color_mediumpurple			0x9370DBFF
#define Color_blueviolet			0x8A2BE2FF
#define Color_darkviolet			0x9400D3FF
#define Color_darkorchid			0x9932CCFF
#define Color_darkmagenta			0x8B008BFF
#define Color_purple				0x800080FF
#define Color_indigo				0x4B0082FF
#define Color_slateblue				0x6A5ACDFF
#define Color_darkslateblue			0x483D8BFF
#define Color_mediumslateblue		0x7B68EEFF
#define Color_greenyellow			0xADFF2FFF
#define Color_chartreuse			0x7FFF00FF
#define Color_lawngreen				0x7CFC00FF
#define Color_lime					0x00FF00FF
#define Color_limegreen				0x32CD32FF
#define Color_palegreen				0x98FB98FF
#define Color_lightgreen			0x90EE90FF
#define Color_mediumspringgreen		0x00FA9AFF
#define Color_springgreen			0x00FF7FFF
#define Color_mediumseagreen		0x3CB371FF
#define Color_seagreen				0x2E8B57FF
#define Color_forestgreen			0x228B22FF
#define Color_green					0x008000FF
#define Color_darkgreen				0x006400FF
#define Color_yellowgreen			0x9ACD32FF
#define Color_olivedrab				0x6B8E23FF
#define Color_olive					0x808000FF
#define Color_darkolivegreen		0x556B2FFF
#define Color_mediumaquamarine		0x66CDAAFF
#define Color_darkseagreen			0x8FBC8FFF
#define Color_lightseagreen			0x20B2AAFF
#define Color_darkcyan				0x008B8BFF
#define Color_teal					0x008080FF
#define Color_aqua					0x00FFFFFF
#define Color_cyan					0x00FFFFFF
#define Color_lightcyan				0xE0FFFFFF
#define Color_paleturquoise			0xAFEEEEFF
#define Color_aquamarine			0x7FFFD4FF
#define Color_turquoise				0x40E0D0FF
#define Color_mediumturquoise		0x48D1CCFF
#define Color_darkturquoise			0x00CED1FF
#define Color_cadetblue				0x5F9EA0FF
#define Color_steelblue				0x4682B4FF
#define Color_lightsteelblue		0xB0C4DEFF
#define Color_powderblue			0xB0E0E6FF
#define Color_lightblue				0xADD8E6FF
#define Color_skyblue				0x87CEEBFF
#define Color_lightskyblue			0x87CEFAFF
#define Color_deepskyblue			0x00BFFFFF
#define Color_dodgerblue			0x1E90FFFF
#define Color_cornflowerblue		0x6495EDFF
#define Color_mediumslateblue		0x7B68EEFF
#define Color_royalblue				0x4169E1FF
#define Color_blue					0x0000FFFF
#define Color_mediumblue			0x0000CDFF
#define Color_darkblue				0x00008BFF
#define Color_navy					0x000080FF
#define Color_midnightblue			0x191970FF
#define Color_cornsilk				0xFFF8DCFF
#define Color_blanchedalmond		0xFFEBCDFF
#define Color_bisque				0xFFE4C4FF
#define Color_navajowhite			0xFFDEADFF
#define Color_wheat					0xF5DEB3FF
#define Color_burlywood				0xDEB887FF
#define Color_tan					0xD2B48CFF
#define Color_rosybrown				0xBC8F8FFF
#define Color_sandybrown			0xF4A460FF
#define Color_goldenrod				0xDAA520FF
#define Color_darkgoldenrod			0xB8860BFF
#define Color_peru					0xCD853FFF
#define Color_chocolate				0xD2691EFF
#define Color_saddlebrown			0x8B4513FF
#define Color_sienna				0xA0522DFF
#define Color_brown					0xA52A2AFF
#define Color_maroon				0x800000FF
#define Color_white					0xFFFFFFFF
#define Color_snow					0xFFFAFAFF
#define Color_honeydew				0xF0FFF0FF
#define Color_mintcream				0xF5FFFAFF
#define Color_azure					0xF0FFFFFF
#define Color_aliceblue				0xF0F8FFFF
#define Color_ghostwhite			0xF8F8FFFF
#define Color_whitesmoke			0xF5F5F5FF
#define Color_seashell				0xFFF5EEFF
#define Color_beige					0xF5F5DCFF
#define Color_oldlace				0xFDF5E6FF
#define Color_floralwhite			0xFFFAF0FF
#define Color_ivory					0xFFFFF0FF
#define Color_antiquewhite			0xFAEBD7FF
#define Color_linen					0xFAF0E6FF
#define Color_lavenderblush			0xFFF0F5FF
#define Color_mistyrose				0xFFE4E1FF
#define Color_gainsboro				0xDCDCDCFF
#define Color_lightgrey				0xD3D3D3FF
#define Color_silver				0xC0C0C0FF
#define Color_darkgray				0xA9A9A9FF
#define Color_gray					0x808080FF
#define Color_dimgray				0x696969FF
#define Color_lightslategray		0x778899FF
#define Color_slategray				0x708090FF
#define Color_darkslategray			0x2F4F4FFF
#define Color_black					0x000000FF

//EOF